force-app/main/default/objects/Margin__c/Margin__c.object-meta.xml
<CustomObject>
    <label>Margem</label>
    <nameField>
        <label>Margem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margin__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarquia de Produto</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/MarginPercentage__c.field-meta.xml
<CustomField>
    <fullName>MarginPercentage__c</fullName>
    <label>Porcentagem De Margem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/motorBusca/MarginPricingEngine.cls
public class MarginPricingEngine implements IPricingEngine {

    public void calculatePrice(List<OrderItem> items, PricingContext context) {
        Map<String, Margin__c> rulesMap = MarginSelector.getRulesMap(
            context.margin.productIds,
            context.margin.hierarchyIds,
            context.margin.locationIds,
            context.margin.dcIds,
            context.margin.accountIds,
            context.margin.accountGroupIds
        );
        MarginEngine engine = new MarginEngine(rulesMap);

        for (OrderItem item : items) {
            Order order = context.mapOrders.get(item.OrderId);
            Id hId = context.mapProducts.get(item.Product2Id)?.ProductHierarchy__c;
            MarginContext ctx = new MarginContext(item, order, hId);
            Margin__c result = engine.find(ctx);

            if (result != null) {
                item.MarginPercentage__c = result.Cost__c;
            } else {
                item.addError('Error: Margin rule not found. Sale of this product is not authorized due to missing pricing parameters. Contact the Pricing team.');
            }
        }
    }

}