force-app/main/default/objects/Tax__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estado</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/TaxCost__c.field-meta.xml
<CustomField>
    <fullName>TaxCost__c</fullName>
    <label>Imposto Sobre Custo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/taxTriggerClass/TaxSelector.cls
public class TaxSelector {
    public static Map<String, Tax__c> getRulesMap(Set<Id> productIds, Set<Id> locationIds, Set<Id> dcIds) {
        Map<String, Tax__c> rulesMap = new Map<String, Tax__c>();

        List<Tax__c> taxes =[
            SELECT Id, TaxCost__c, Product__c, State__c, DistributionCenter__c
            FROM Tax__c
            WHERE Status__c = 'Approved'
            AND DistributionCenter__c IN :dcIds
            AND Product__c IN :productIds];

        for (Tax__c t : taxes) {
            String masterKey = String.valueOf(t.Product__c) +
                         String.valueOf(t.DistributionCenter__c) +
                         String.valueOf(t.State__c);
            rulesMap.put(masterKey, t);
        }
        return rulesMap;
    }
}