force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <label>Frete</label>
    <nameField>
        <label>Frete Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fretes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Freight__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarquia de Produto</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Fretes</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FreightCost__c.field-meta.xml
<CustomField>
    <fullName>FreightCost__c</fullName>
    <label>Custo De Frete</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/motorBusca/FreightPricingEngine.cls
public class FreightPricingEngine implements IPricingEngine {

    public void calculatePrice(List<OrderItem> itens, PricingContext context) {
        Map<String, Freight__c> mapaRegras = FreightSelector.getMapaRegras(
            context.frete.produtosIds,
            context.frete.hierarquiasIds,
            context.frete.locaisIds,
            context.frete.cdsIds
        );
        FreightEngine motor = new FreightEngine(mapaRegras);

        for (OrderItem item : itens) {
            Order ped = context.mapPedidos.get(item.OrderId);
            Id hId = context.mapProdutos.get(item.Product2Id)?.ProductHierarchy__c;
            FreightContext ctx = new FreightContext(item, ped, hId);
            Freight__c resultado = motor.buscar(ctx);

            if (resultado != null) {
                item.FreightCost__c = resultado.Cost__c;
            } else {
                item.addError('Erro: Frete não existe. Não está autorizada a venda deste produto devido à falta de parâmetros. Contate o time de Pricing.');
            }
        }
    }

}