force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Estado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Imposto__c/fields/Centro_Distribuicao__c.field-meta.xml
<CustomField>
    <fullName>Centro_Distribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Imposto_Custo__c.field-meta.xml
<CustomField>
    <fullName>Imposto_Custo__c</fullName>
    <label>Imposto Sobre Custo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Imposto__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/motorBusca/imposto/ImpostoSelector.cls
public class ImpostoSelector {
    public static Map<String, Imposto__c> getMapaRegras(Set<Id> produtosIds, Set<Id> locaisIds, Set<Id> cdsIds) {
        Map<String, Imposto__c> mapaRegras = new Map<String, Imposto__c>();

        // A Query Única
        // O CD aqui serve apenas para restringir o universo de busca
        List<Imposto__c> impostos = [
            SELECT Id, Imposto_Custo__c, Product__c, Estado__c, Centro_Distribuicao__c
            FROM Imposto__c
            WHERE Status__c = 'Aprovado'
            AND Centro_Distribuicao__c IN :cdsIds 
            AND Product__c IN :produtosIds  
            
            
        ];
        System.debug(impostos + ' | ' + 'impostos encontrados para os cds');


        // Montagem da Chave Composta
        for (Imposto__c i : impostos) {
            String chaveMestra = String.valueOf(i.Product__c) + 
                         String.valueOf(i.Centro_Distribuicao__c) + 
                         String.valueOf(i.Estado__c);
    
        mapaRegras.put(chaveMestra, i);
            
        }
        return mapaRegras;
    }
}