force-app/main/default/objects/Product2/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hierarquia de Produto</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>CountryStatesRef</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estado</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Impostos</relationshipLabel>
    <relationshipName>Impostos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/TaxCost__c.field-meta.xml
<CustomField>
    <fullName>TaxCost__c</fullName>
    <label>Imposto Sobre Custo</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/force-app-test/taxTest/TaxSelectorTest.cls
@isTest
private class TaxSelectorTest {

    @testSetup
    static void setupTestData() {
        Id pricebookId = Test.getStandardPricebookId();
        update new Pricebook2(Id = pricebookId, IsActive = true);

        DistributionCenter__c dc = (DistributionCenter__c) TestFactorySObject.getInstance().createSObject(new DistributionCenter__c());
        insert dc;

        ProductHierarchy__c hierarchy = (ProductHierarchy__c) TestFactorySObject.getInstance().createSObject(new ProductHierarchy__c());
        insert hierarchy;

        Product2 product = (Product2) TestFactorySObject.getInstance().createSObject(new Product2());
        product.ProductHierarchy__c = hierarchy.Id;
        insert product;

        Country__c country = (Country__c) TestFactorySObject.getInstance().createSObject(new Country__c());
        insert country;

        State__c state = (State__c) TestFactorySObject.getInstance().createSObject(new State__c());
        state.Country__c = country.Id;
        insert state;
    }

    @isTest
    static void shouldRetrieveTax() {
        Set<Id> productsIds = new Set<Id>();
        Set<Id> locationsIds = new Set<Id>();
        Set<Id> dcsIds = new Set<Id>();

        DistributionCenter__c dc = [SELECT Id FROM DistributionCenter__c LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];
        State__c state = [SELECT Id FROM State__c LIMIT 1];

        Tax__c tax = (Tax__c) TestFactorySObject.getInstance().createSObject(new Tax__c());
        tax.DistributionCenter__c = dc.Id;
        tax.Product__c = product.Id;
        tax.State__c = state.Id;
        insert tax;

        Tax__c taxQueried = [SELECT Id, Name, DistributionCenter__c, Product__c, State__c, TaxCost__c FROM Tax__c LIMIT 1];

        for(DistributionCenter__c d : [SELECT Id FROM DistributionCenter__c]) {
            System.debug('Distribution Center: ' + d.Id);
            dcsIds.add(d.Id);
        }
        for(Product2 p : [SELECT Id FROM Product2]) {
            System.debug('Product: ' + p.Id);
            productsIds.add(p.Id);
        }
        for(State__c s : [SELECT Id FROM State__c]) {
            System.debug('State: ' + s.Id);
            locationsIds.add(s.Id);
        }

        Map<String, Tax__c> taxes = TaxSelector.getRulesMap(productsIds, locationsIds, dcsIds);

        String masterKey = String.valueOf(tax.Product__c) +
                         String.valueOf(tax.DistributionCenter__c) +
                         String.valueOf(tax.State__c);

        Assert.isTrue(taxes.containsKey(masterKey));
    }
}