force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enderecos</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Enderecos</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <label>Bairro</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <externalId>true</externalId>
    <label>CEP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Logradouro</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>Cidade</label>
    <nameField>
        <label>Cidade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estado</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>CountryStatesRef</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/force-app-test/address-test/AddressTest.cls
@isTest
private class AddressTest {

    @TestSetup
    static void makeData(){
        AccountGroup__c accountGroup = (AccountGroup__c) TestFactorySObject.getInstance().createSObject(new AccountGroup__c());
        insert accountGroup;

        Account account = (Account) TestFactorySObject.getInstance().createSObject(new Account());
        account.AccountGroup__c = accountGroup.Id;
        insert account;

        Country__c country = (Country__c) TestFactorySObject.getInstance().createSObject(new Country__c());
        insert country;

        State__c state = (State__c) TestFactorySObject.getInstance().createSObject(new State__c());
        state.Country__c = country.Id;
        insert state;

        City__c city = (City__c) TestFactorySObject.getInstance().createSObject(new City__c());
        city.State__c = state.Id;
        insert city;
    }

    @isTest
    static void shouldCreateAddress() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        City__c city = [SELECT Id FROM City__c LIMIT 1];

        Address__c address = (Address__c) TestFactorySObject.getInstance().createSObject(new Address__c());
        address.Account__c = account.Id;
        address.City__c = city.Id;

        try{
            insert address;

            Address__c inserted = [SELECT Id, Name, Street__c, Neighborhood__c, PostalCode__c, Account__c, City__c FROM Address__c WHERE Id = :address.Id];

            System.debug('Address inserted: ' + inserted + inserted.Id);
            Assert.isNotNull(inserted.Id, 'Expected: Id should not be null');

            Assert.areEqual(address.Account__c, inserted.Account__c, 'Expected: Account should match');
            Assert.areEqual(address.City__c, inserted.City__c, 'Expected: City should match');
            Assert.areEqual(address.Name, inserted.Name, 'Expected: Name should match');
            Assert.areEqual(address.Street__c, inserted.Street__c, 'Expected: Street should match');
            Assert.areEqual(address.Neighborhood__c, inserted.Neighborhood__c, 'Expected: Neighborhood should match');
            Assert.areEqual(address.PostalCode__c, inserted.PostalCode__c, 'Expected: PostalCode should match');

        } catch (DmlException e) {
            System.debug('Unexpected error: ' + e.getMessage());
            Assert.fail('Expected: DmlException was not expected');
        }
    }

    @isTest
    static void shouldNotCreateAddressWithoutName() {
        City__c city = [SELECT Id FROM City__c LIMIT 1];
        Account account = [SELECT Id FROM Account LIMIT 1];

        Address__c address = (Address__c) TestFactorySObject.getInstance().createSObject(new Address__c());
        address.Name = null;
        address.City__c = city.Id;
        address.Account__c = account.Id;

        try{
            insert address;
            Assert.fail('Expected: DmlException was expected due to missing Name');
        } catch (DmlException e) {
            System.debug('Expected error: ' + e.getMessage());
            Assert.isNull(address.Name);
            Assert.isTrue(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'), 'Expected: DmlException should indicate FIELD_CUSTOM_VALIDATION_EXCEPTION');
        }
    }
}