force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Enderecos</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>Cidade</label>
    <nameField>
        <label>Cidade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estado</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Endereco</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>CountryStatesRef</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/motorBusca/margin/MarginContext.cls
public with sharing class MarginContext {
    public Id pId;    // Product
    public Id hId;    // Product Hierarchy
    public Id cntId;  // Account
    public Id hCntId; // Account Group
    public Id cdId;   // Distribution Center
    public Id paiId;  // Country
    public Id estId;  // State
    public Id cidId;  // City

    public MarginContext(OrderItem item, Order order, Id hierarchyId) {
        this.pId    = item.Product2Id;
        this.hId    = hierarchyId;
        this.cntId  = order.AccountId;
        this.hCntId = (order.Account != null) ? order.Account.AccountGroup__c : null;
        this.cdId   = order.DistributionCenter__c;

        if (order.Address__c != null) {
            this.cidId = order.Address__r.City__c;
            this.estId = order.Address__r.City__r?.State__c;
            this.paiId = order.Address__r.City__r?.State__r?.Country__c;
        }
    }
}