force-app/main/default/objects/Account/fields/Grupo_Clientes__c.field-meta.xml
<CustomField>
    <fullName>Grupo_Clientes__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>Grupo_Conta__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Centro_de_Distribuicao__c/Centro_de_Distribuicao__c.object-meta.xml
<CustomObject>
    <label>Centro de Distribuicao</label>
    <nameField>
        <label>Centro de Distribuição Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centro de Distribuições</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Estado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grupo_Conta__c/Grupo_Conta__c.object-meta.xml
<CustomObject>
    <label>Grupo De Conta</label>
    <nameField>
        <label>Grupo De Conta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupo De Contas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hierarquia_Produto__c/Hierarquia_Produto__c.object-meta.xml
<CustomObject>
    <label>Hierarquia de Produto</label>
    <nameField>
        <label>Hierarquia de Produto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquia de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/Centro_Distribuicao__c.field-meta.xml
<CustomField>
    <fullName>Centro_Distribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Grupo_Conta__c.field-meta.xml
<CustomField>
    <fullName>Grupo_Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo De Conta</label>
    <referenceTo>Grupo_Conta__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Hierarquia_Produto__c.field-meta.xml
<CustomField>
    <fullName>Hierarquia_Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarquia de Produto</label>
    <referenceTo>Hierarquia_Produto__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Centro_Distribuicao__c.field-meta.xml
<CustomField>
    <fullName>Centro_Distribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>Pais</label>
    <nameField>
        <label>País Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Hierarquia_Produto__c.field-meta.xml
<CustomField>
    <fullName>Hierarquia_Produto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hierarquia de Produto</label>
    <referenceTo>Hierarquia_Produto__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/force-app-test/margem-test/MargemTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class MargemTest {

    @testSetup
    static void setupTestData() {

         Id pricebookId = Test.getStandardPricebookId();
        update new Pricebook2(Id = pricebookId, IsActive = true);

        Centro_de_Distribuicao__c centro = (Centro_de_Distribuicao__c) TestFactorySObject.getInstance().createSObject(new Centro_de_Distribuicao__c());
        insert centro;

        Grupo_Conta__c grupoConta = (Grupo_Conta__c) TestFactorySObject.getInstance().createSObject(new Grupo_Conta__c());
        insert grupoConta;
        Account account = (Account) TestFactorySObject.getInstance().createSObject(new Account());
        account.Grupo_Clientes__c = grupoConta.Id;
        insert account;

        Hierarquia_Produto__c hierarquia = (Hierarquia_Produto__c) TestFactorySObject.getInstance().createSObject(new Hierarquia_Produto__c());
        insert hierarquia;
        Product2 product = (Product2) TestFactorySObject.getInstance().createSObject(new Product2());
        product.Hierarquia_Produto__c = hierarquia.Id;
        insert product;

        Pais__c pais = (Pais__c) TestFactorySObject.getInstance().createSObject(new Pais__c());
        insert pais;

        Estado__c estado = (Estado__c) TestFactorySObject.getInstance().createSObject(new Estado__c());
        estado.Pais__c = pais.Id;
        insert estado;

        Cidade__c cidade = (Cidade__c) TestFactorySObject.getInstance().createSObject(new Cidade__c());
        cidade.Estado__c = estado.Id;
        insert cidade;
    }

    @isTest
    static void shouldValidateXorPaisEstadoCidadeContaGrupoContaProdutoHierarquiaDeProduto() {
        Pais__c pais = [SELECT Id FROM Pais__c LIMIT 1][0];
        Estado__c estado = [SELECT Id FROM Estado__c LIMIT 1][0];
        Cidade__c cidade = [SELECT Id FROM Cidade__c LIMIT 1][0];
        Account conta = [SELECT Id FROM Account LIMIT 1][0];
        Grupo_Conta__c grupoConta = [SELECT Id FROM Grupo_Conta__c LIMIT 1][0];
        Product2 produto = [SELECT Id FROM Product2 LIMIT 1][0];
        Hierarquia_Produto__c hierarquia = [SELECT Id FROM Hierarquia_Produto__c LIMIT 1][0];
        Centro_de_Distribuicao__c cd = [SELECT Id FROM Centro_de_Distribuicao__c LIMIT 1][0];

        Margem__c margemValida = (Margem__c)TestFactorySObject.getInstance().createSObject(new Margem__c(
            Cidade__c = cidade.Id,
            Conta__c = conta.Id,
            Produto__c = produto.Id,
            Centro_Distribuicao__c = cd.Id
        ));
        insert margemValida;
        System.assertNotEquals(null, margemValida.Id);

        Margem__c margemInvalida1 = (Margem__c)TestFactorySObject.getInstance().createSObject(new Margem__c(
            Cidade__c = cidade.Id,
            Estado__c = estado.Id,
            Conta__c = conta.Id,
            Produto__c = produto.Id,
            Centro_Distribuicao__c = cd.Id
        ));
        try {
            insert margemInvalida1;
            System.assert(false);
        } catch (DmlException e1) {
            System.assert(e1.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }

        Margem__c margemInvalida2 = (Margem__c)TestFactorySObject.getInstance().createSObject(new Margem__c(
            Cidade__c = cidade.Id,
            Conta__c = conta.Id,
            Grupo_Conta__c = grupoConta.Id,
            Produto__c = produto.Id,
            Centro_Distribuicao__c = cd.Id
        ));
        try {
            insert margemInvalida2;
            System.assert(false);
        } catch (DmlException e2) {
            System.assert(e2.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }

        Margem__c margemInvalida3 = (Margem__c)TestFactorySObject.getInstance().createSObject(new Margem__c(
            Cidade__c = cidade.Id,
            Conta__c = conta.Id,
            Produto__c = produto.Id,
            Hierarquia_Produto__c = hierarquia.Id,
            Centro_Distribuicao__c = cd.Id
        ));
        try {
            insert margemInvalida3;
            System.assert(false);
        } catch (DmlException e3) {
            System.assert(e3.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }

        Margem__c margemSemCD = (Margem__c)TestFactorySObject.getInstance().createSObject(new Margem__c(
            Cidade__c = cidade.Id,
            Conta__c = conta.Id,
            Produto__c = produto.Id
        ));
        try {
            insert margemSemCD;
            System.assert(false);
        } catch (DmlException e4) {
            System.assert(e4.getMessage().contains('REQUIRED_FIELD_MISSING'));
        }
    }
}