force-app/main/default/objects/Account/fields/Grupo_Clientes__c.field-meta.xml
<CustomField>
    <fullName>Grupo_Clientes__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>Grupo_Conta__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Endereco__c/Endereco__c.object-meta.xml
<CustomObject>
    <label>Endereco</label>
    <nameField>
        <label>Endereco Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enderecos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Endereco__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Enderecos</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Estado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hierarquia_Produto__c/Hierarquia_Produto__c.object-meta.xml
<CustomObject>
    <label>Hierarquia de Produto</label>
    <nameField>
        <label>Hierarquia de Produto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquia de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Centro_Distribuicao__c.field-meta.xml
<CustomField>
    <fullName>Centro_Distribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Endereco</label>
    <referenceTo>Endereco__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>Pais</label>
    <nameField>
        <label>País Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Hierarquia_Produto__c.field-meta.xml
<CustomField>
    <fullName>Hierarquia_Produto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hierarquia de Produto</label>
    <referenceTo>Hierarquia_Produto__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/motorBusca/margem/ContextoMargem.cls
public with sharing class ContextoMargem {
    public ContextoMargem() {

    }
    public Id pId;   // Produto
    public Id hId;   // Hierarquia produto
    public Id cntId; // conta
    public Id hCntId; // hierarquia conta
    public Id cdId;  // Centro de Distribuição 
    public Id paiId; // País
    public Id estId; // Estado
    public Id cidId; // Cidade

    // Construtor para facilitar a criação dentro do loop
    public ContextoMargem(OrderItem item, Order ped) {
        this.pId    = item.Product2Id;
        this.hId    = (item.Product2 != null) ? item.Product2.Hierarquia_Produto__c : null;
        this.cntId  = ped.AccountId;
        this.hCntId = (ped.Account != null) ? ped.Account.Grupo_Clientes__c : null;
        this.cdId   = ped.Centro_Distribuicao__c;
        
        if(ped.Endereco__c!= null) {
            this.cidId = ped.Endereco__r.Cidade__c;
            this.estId = ped.Endereco__r.Cidade__r.Estado__c;
            this.paiId = ped.Endereco__r.Cidade__r.Estado__r.Pais__c;

            
            
        }
    }
}