force-app/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Estado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grupo_Conta__c/Grupo_Conta__c.object-meta.xml
<CustomObject>
    <label>Grupo De Conta</label>
    <nameField>
        <label>Grupo De Conta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupo De Contas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hierarquia_Produto__c/Hierarquia_Produto__c.object-meta.xml
<CustomObject>
    <label>Hierarquia de Produto</label>
    <nameField>
        <label>Hierarquia de Produto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquia de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margem__c/fields/Centro_Distribuicao__c.field-meta.xml
<CustomField>
    <fullName>Centro_Distribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Grupo_Conta__c.field-meta.xml
<CustomField>
    <fullName>Grupo_Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo De Conta</label>
    <referenceTo>Grupo_Conta__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Hierarquia_Produto__c.field-meta.xml
<CustomField>
    <fullName>Hierarquia_Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarquia de Produto</label>
    <referenceTo>Hierarquia_Produto__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margem__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>Pais</label>
    <nameField>
        <label>País Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/margemTriggerClass/MargemService.cls
public with sharing class MargemService {

    public static void validarDuplicidadeMargem(List<Margem__c> margens){
        Set<String> chavesNovas = new Set<String>();
        Set<Id> chavesExistentes = new Set<id>();
        
        for (Margem__c m : margens) {
            String chave = gerarChave(m);
            System.debug('Chave gerada para validação: ' + chave);
            
            if (chavesNovas.contains(chave)) {
                m.addError('Erro: Você está tentando inserir registros duplicados no mesmo lote para a combinação: ' + chave);
            }
            chavesNovas.add(chave);

            if (m.Id != null) {
                chavesExistentes.add(m.Id);
            }
        }

        Map<String, Margem__c> mapaExistentes = new Map<String, Margem__c>();
        
       
        for (Margem__c existente : [SELECT Id, Produto__c, Hierarquia_Produto__c, Conta__c, Centro_Distribuicao__c,
                                    Grupo_Conta__c, Cidade__c, Estado__c, Pais__c 
                                    FROM Margem__c 
                                    WHERE Id NOT IN :chavesExistentes]) {
            
            
            mapaExistentes.put(gerarChave(existente), existente);
        }


        for (Margem__c nova : margens) {
        String chaveNova = gerarChave(nova);
        if (mapaExistentes.containsKey(chaveNova)) {
            nova.addError('Já existe um registro de Margem Ativo com esta exata combinação de Produto/Cliente/Localidade/Centro de Distribuição.');
        }
        }
    }

    private static String gerarChave(Margem__c m) {
        return  (m.Produto__c != null ? (String)m.Produto__c : (String)m.Hierarquia_Produto__c) + '|' +
                (m.Conta__c != null ? (String)m.Conta__c : (String)m.Grupo_Conta__c) + '|' +
                (m.Centro_Distribuicao__c != null ? (String)m.Centro_Distribuicao__c : 'SemCD') + '|' + 
                (m.Cidade__c != null ? (String)m.Cidade__c : 
                (m.Estado__c != null ? (String)m.Estado__c : (String)m.Pais__c));
    }
}