force-app/main/default/objects/Endereco__c/Endereco__c.object-meta.xml
<CustomObject>
    <label>Endereco</label>
    <nameField>
        <label>Endereco Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enderecos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Endereco__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Enderecos</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Estado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Centro_Distribuicao__c.field-meta.xml
<CustomField>
    <fullName>Centro_Distribuicao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>Centro_de_Distribuicao__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Endereco</label>
    <referenceTo>Endereco__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/motorBusca/imposto/ContextoImposto.cls
public with sharing class ContextoImposto {
    public ContextoImposto() {

    }
    public Id pId;   // Produto
    public Id cdId;  // Centro de Distribuição 
    public Id estId; // Estado

    // Construtor para facilitar a criação dentro do loop
    public ContextoImposto(OrderItem item, Order ped) {
        this.pId   = item.Product2Id;
        this.cdId  = ped.Centro_Distribuicao__c;
        
        if(ped.Endereco__r != null) {
            this.estId = ped.Endereco__r.Cidade__r?.Estado__c; // O ?. evita erro se Cidade for nula
        }

    }
}