force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>Cidade</label>
    <nameField>
        <label>Cidade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Estado</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cidades</relationshipLabel>
    <relationshipName>Cidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/Margin__c.object-meta.xml
<CustomObject>
    <label>Margem</label>
    <nameField>
        <label>Margem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Margens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margin__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo De Conta</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centro de Distribuicao</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarquia de Produto</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Margens</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Reprovado</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <label>Bloqueado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pais</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>CountryStatesRef</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/marginTriggerClass/MarginService.cls
public with sharing class MarginService {

    public static void validarDuplicidadeMargem(List<Margin__c> margens){
        Set<String> chavesNovas = new Set<String>();
        Set<Id> chavesExistentes = new Set<Id>();
        Set<Id> produtosNovos    = new Set<Id>();
        Set<Id> hierarquiasNovas = new Set<Id>();
        Set<Id> contasNovas      = new Set<Id>();
        Set<Id> gruposNovos      = new Set<Id>();

        for (Margin__c m : margens) {
            String chave = gerarChave(m);
            System.debug('Chave gerada para validação: ' + chave);

            if (chavesNovas.contains(chave)) {
                m.addError('Erro: Você está tentando inserir registros duplicados no mesmo lote para a combinação: ' + chave);
            }
            chavesNovas.add(chave);

            if (m.Id != null)                  chavesExistentes.add(m.Id);
            if (m.Product__c != null)          produtosNovos.add(m.Product__c);
            if (m.ProductHierarchy__c != null) hierarquiasNovas.add(m.ProductHierarchy__c);
            if (m.Account__c != null)          contasNovas.add(m.Account__c);
            if (m.AccountGroup__c != null)     gruposNovos.add(m.AccountGroup__c);
        }

        Map<String, Margin__c> mapaExistentes = new Map<String, Margin__c>();

        for (Margin__c existente : [SELECT Id, Product__c, ProductHierarchy__c, Account__c,
                                    AccountGroup__c, City__c, State__c, Country__c, DistributionCenter__c
                                    FROM Margin__c
                                    WHERE Status__c = 'Approved'
                                    AND Id NOT IN :chavesExistentes
                                    AND (Product__c IN :produtosNovos OR ProductHierarchy__c IN :hierarquiasNovas)
                                    AND (Account__c IN :contasNovas OR AccountGroup__c IN :gruposNovos)]) {

            mapaExistentes.put(gerarChave(existente), existente);
        }


        for (Margin__c nova : margens) {
        String chaveNova = gerarChave(nova);
        if (mapaExistentes.containsKey(chaveNova)) {
            nova.addError('Já existe um registro de Margem Ativo com esta exata combinação de Produto/Cliente/Localidade/Centro de Distribuição.');
        }
        }
    }

    private static String gerarChave(Margin__c m) {
        return  (m.Product__c != null ? (String)m.Product__c : (String)m.ProductHierarchy__c) + '|' +
                (m.Account__c != null ? (String)m.Account__c : (String)m.AccountGroup__c) + '|' +
                (m.DistributionCenter__c != null ? (String)m.DistributionCenter__c : 'SemCD') + '|' +
                (m.City__c != null ? (String)m.City__c :
                (m.State__c != null ? (String)m.State__c : (String)m.Country__c));
    }
}