force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>Pais</label>
    <nameField>
        <label>País Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/force-app-test/pais-test/PaistTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PaistTest {

    @isTest
    static void shouldCreatePais() {
        // Arrange
        Pais__c pais = (Pais__c) TestFactorySObject.getInstance().createSObject(new Pais__c());

        Test.startTest();
       try{
        insert pais;
        System.debug('Pais__c inserted successfully with Id: ' + pais.Id);
        System.assert(true,'Expected: DmlException was not thrown');
       
        }catch(DmlException e){
        
            System.assert(false,'Unexpected DmlException was thrown: ' + e.getMessage());


       }
       Test.stopTest();
    }

    @isTest
    static void shouldFailWhenCreatingPaisWithoutName() {
        // Arrange
        Pais__c pais = (Pais__c) TestFactorySObject.getInstance().createSObject(new Pais__c());
        pais.Name = null;

        Test.startTest();
       try{
        insert pais;
        System.debug('Pais__c inserted successfully with Id: ' + pais.Id);
        System.assert(false,'Expected: DmlException was not thrown');
       
        }catch(DmlException e){
        
            System.assert(true,'Unexpected DmlException was thrown: ' + e.getMessage());


       }
       Test.stopTest();
    }

    @isTest
    static void shouldFailWhenCreatingPaisWithoutSigla() {
        // Arrange
        Pais__c pais = (Pais__c) TestFactorySObject.getInstance().createSObject(new Pais__c());
        pais.Sigla__c = null;

        Test.startTest();
       try{
        insert pais;
        System.debug('Pais__c inserted successfully with Id: ' + pais.Id);
        System.assert(false,'Expected: DmlException was not thrown');
       
        }catch(DmlException e){
        
            System.assert(true,'Unexpected DmlException was thrown: ' + e.getMessage());


       }
       Test.stopTest();
    }
}