force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Meta</label>
    <nameField>
        <label>Meta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal_Condition_Payment__c/Goal_Condition_Payment__c.object-meta.xml
<CustomObject>
    <label>Condição De Pagamento Da Meta</label>
    <nameField>
        <label>Condição De Pagamento Da Meta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições De Pagamento Da Meta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GoalItem__c/GoalItem__c.object-meta.xml
<CustomObject>
    <label>Item Da Meta</label>
    <nameField>
        <label>Item Da Meta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens Das Metas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GoalItem__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <label>Meta</label>
    <referenceTo>Goal__c</referenceTo>
    <relationshipLabel>Itens Das Metas</relationshipLabel>
    <relationshipName>Itens_Das_Metas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/Goal_Amount__c.field-meta.xml
<CustomField>
    <fullName>Goal_Amount__c</fullName>
    <label>Valor Da Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/Goal_Condition_Payment__c.field-meta.xml
<CustomField>
    <fullName>Goal_Condition_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição De Pagamento Da Meta</label>
    <referenceTo>Goal_Condition_Payment__c</referenceTo>
    <relationshipLabel>Itens Das Metas</relationshipLabel>
    <relationshipName>Itens_Das_Metas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/Goal_Product__c.field-meta.xml
<CustomField>
    <fullName>Goal_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto Da Meta</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens Das Metas</relationshipLabel>
    <relationshipName>Itens_Das_Metas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/Negotiated_Value__c.field-meta.xml
<CustomField>
    <fullName>Negotiated_Value__c</fullName>
    <label>Valor Negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Familia De Produto</label>
    <referenceTo>Product_Family__c</referenceTo>
    <relationshipLabel>Itens Das Metas</relationshipLabel>
    <relationshipName>Itens_Das_Metas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/Projected_Amount__c.field-meta.xml
<CustomField>
    <fullName>Projected_Amount__c</fullName>
    <label>Valor Projetado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GoalItem__c/fields/Realized_Value__c.field-meta.xml
<CustomField>
    <fullName>Realized_Value__c</fullName>
    <label>Valor Realizado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Family__c/Product_Family__c.object-meta.xml
<CustomObject>
    <label>Familia De Produto</label>
    <nameField>
        <label>Familia De Produto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Familia De Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/goalChallenge/repositories/GoalItemRepository.cls
public with sharing class GoalItemRepository implements IGoalItemRepository {

    public List<GoalItem_DTO> findByGoals(Set<Id> goalIds) {
        List<GoalItem_DTO> result = new List<GoalItem_DTO>();

        for (GoalItem__c gi : [
                SELECT Id, Goal__c, RecordType.DeveloperName,
                       Goal_Product__c, Product_Family__r.Name, Goal_Condition_Payment__r.Name,
                       Goal_Amount__c, Projected_Amount__c, Negotiated_Value__c, Realized_Value__c
                FROM GoalItem__c
                WHERE Goal__c IN :goalIds
        ]) {
            GoalItem_DTO dto = new GoalItem_DTO();
            dto.id = gi.Id;
            dto.goalId = gi.Goal__c;
            dto.recordTypeDeveloperName = gi.RecordType.DeveloperName;
            dto.productId = gi.Goal_Product__c;
            dto.productFamily = gi.Product_Family__r.Name;
            dto.paymentCondition = gi.Goal_Condition_Payment__r.Name;
            dto.target = gi.Goal_Amount__c;
            dto.projected = gi.Projected_Amount__c;
            dto.negotiated = gi.Negotiated_Value__c;
            dto.realized = gi.Realized_Value__c;
            result.add(dto);
        }
        return result;
    }
}